<?php

/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">

<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Laminas MVC Skeleton')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink([
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico'
    ])
        ->prependStylesheet($this->basePath('css/style.css'))
        //->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ->prependStylesheet('https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css');
    ?>
    <!-- Scripts -->
    <?= $this->headScript() ?>
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark mb-4" role="navigation">
        <div class="container">
            <a class="navbar-brand" href="<?= $this->url('home') ?>">
                <img src="<?= $this->basePath('img/logo-h70.png') ?>" alt="SEWorqs">
            </a>
            <div class="text-light pt-2 ms-3">
                <?php echo $this->partial('seworqs/partial/user'); ?>
            </div>
        </div>
    </nav>
    <div class="container">
        <?= $this->content ?>
        <hr>
        <footer>
            <p>
                &copy; <?= date('Y') ?>
                <a href="https://seworqs.nl">SEWorqs</a> a Series of SEWorqs Laminas Modules.
            </p>
        </footer>
    </div>
    <?= $this->inlineScript()
        //->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile('https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.min.js')
        ->prependFile('https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js')
    ?>
</body>

</html>